import { create } from "zustand";
import { createJSONStorage, persist } from "zustand/middleware";
import { getActiveWalletId, setActiveWallet, walletAdapter } from "@/lib/wallet";
import { isValidStellarPublicKey } from "@/lib/stellarAddress";

export type WalletErrorKey = "wallet.error.freighterUnavailable" | "wallet.error.connectFailed";
export type PersistedWalletState = { address: string | null; lastKnownAddress: string | null; network: string | null; isConnected: boolean; activeWalletId?: string };
export const PERSIST_KEY = "vortex-wallet";
const EXPECTED_NETWORK = (process.env["NEXT_PUBLIC_NETWORK"] ?? "testnet").toUpperCase();
export type WalletState = PersistedWalletState & { activeWalletId: string; isConnecting: boolean; wasSessionCleared: boolean; error: string | null; errorKey: WalletErrorKey | null; networkMismatch: boolean; notInstalled: boolean; connect: () => Promise<void>; disconnect: () => void; hydrate: () => Promise<void>; checkForChanges: () => Promise<void>; syncFromStorage: (persisted: PersistedWalletState) => void; selectWallet: (id: string) => void };
const mismatch = (network: string) => network.toUpperCase() !== EXPECTED_NETWORK;
export const useWalletStore = create<WalletState>()(persist((set, get) => ({
  address: null, lastKnownAddress: null, network: null, isConnected: false, activeWalletId: getActiveWalletId(), isConnecting: false, wasSessionCleared: false, error: null, errorKey: null, networkMismatch: false, notInstalled: false,
  connect: async () => { set({ isConnecting: true, error: null, errorKey: null, notInstalled: false }); try { if (!(await walletAdapter.isConnected())) { set({ isConnecting: false, isConnected: false, error: "Selected wallet is not installed or enabled.", errorKey: "wallet.error.freighterUnavailable", notInstalled: true }); return; } const address = await walletAdapter.connect(); const network = await walletAdapter.getNetwork(); set({ address, lastKnownAddress: address, network, isConnected: true, isConnecting: false, wasSessionCleared: false, error: null, errorKey: null, networkMismatch: mismatch(network), notInstalled: false }); } catch (error) { const message = error instanceof Error ? error.message : "Failed to connect wallet."; set({ isConnecting: false, isConnected: false, address: null, network: null, error: message, errorKey: error instanceof Error ? null : "wallet.error.connectFailed", networkMismatch: false, notInstalled: false }); } },
  disconnect: () => { void walletAdapter.disconnect(); set({ address: null, network: null, isConnected: false, isConnecting: false, wasSessionCleared: true, error: null, errorKey: null, networkMismatch: false }); },
  selectWallet: (id) => { setActiveWallet(id); set({ activeWalletId: getActiveWalletId(), address: null, network: null, isConnected: false, wasSessionCleared: false }); },
  checkForChanges: async () => { if (!get().isConnected || !(await walletAdapter.isAllowed())) return; try { const address = await walletAdapter.getPublicKey(); const network = await walletAdapter.getNetwork(); set({ address, lastKnownAddress: address, network, networkMismatch: mismatch(network) }); } catch { /* wallet may be temporarily unavailable */ } },
  hydrate: async () => { if (!get().isConnected) return; try { if (!(await walletAdapter.isConnected()) || !(await walletAdapter.isAllowed())) { set({ address: null, network: null, isConnected: false, wasSessionCleared: true }); return; } const address = await walletAdapter.getPublicKey(); const network = await walletAdapter.getNetwork(); set({ address, lastKnownAddress: address, network, isConnected: true, networkMismatch: mismatch(network), wasSessionCleared: false }); } catch { set({ address: null, network: null, isConnected: false, wasSessionCleared: false }); } },
  syncFromStorage: (persisted) => { const current = get(); if (!persisted.isConnected) { set({ address: null, network: null, isConnected: false }); return; } if (persisted.address !== current.address) set({ address: persisted.address, lastKnownAddress: persisted.address, network: persisted.network, isConnected: true }); },
}), { name: PERSIST_KEY, storage: createJSONStorage(() => localStorage), partialize: (state): PersistedWalletState => ({ address: state.address, lastKnownAddress: state.lastKnownAddress, network: state.network, isConnected: state.isConnected, activeWalletId: state.activeWalletId }) }));
export function isValidPersistedWalletState(state: unknown): state is PersistedWalletState { if (!state || typeof state !== "object") return false; const value = state as Record<string, unknown>; return (value.address === null || typeof value.address === "string") && (value.lastKnownAddress === null || typeof value.lastKnownAddress === "string") && (value.network === null || typeof value.network === "string") && typeof value.isConnected === "boolean" && (value.address === null || isValidStellarPublicKey(value.address)); }
